### ISSUE TITLE
Error as a Jenkins plugin

### ISSUE THREAD

**Issue by lalkhum** [puppetlabs/puppet-gatling-jenkins-plugin#11]
Hi @briancain
I use this plugin (latest release) in my load test, and I got the error as follows. I would really appreciate if anyone could point out why this is happening?

ERROR looks like:

[PuppetGatling] - Starting deployment from the post-action ...
ERROR: Publisher 'Puppet Gatling' aborted due to exception: 
java.lang.NoClassDefFoundError: com/excilys/ebi/gatling/jenkins/GatlingBuildAction
    at com.puppetlabs.jenkins.plugins.puppetgatling.PuppetGatlingPublisher.getBuildAction(PuppetGatlingPublisher.java:126)
    at com.puppetlabs.jenkins.plugins.puppetgatling.PuppetGatlingPublisher.perform(PuppetGatlingPublisher.java:100)
    at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
    at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:779)
    at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:726)
    at hudson.model.Build$BuildExecution.post2(Build.java:185)
    at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:671)
    at hudson.model.Run.execute(Run.java:1766)
    at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
    at hudson.model.ResourceController.execute(ResourceController.java:98)
    at hudson.model.Executor.run(Executor.java:408)
Caused by: java.lang.ClassNotFoundException: com.excilys.ebi.gatling.jenkins.GatlingBuildAction
    at jenkins.util.AntClassLoader.findClassInComponents(AntClassLoader.java:1376)
    at jenkins.util.AntClassLoader.findClass(AntClassLoader.java:1326)
    at jenkins.util.AntClassLoader.loadClass(AntClassLoader.java:1079)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
    ... 11 more
Archiving Gatling reports...
Adding report 'curationkitassetsbyguidesquery-1440163741239'

**Comment by MikaelSmith** [comment]
Pretty obviously, this repository is not being actively developed. Sorry you didn't get help when you asked. I'm closing this issue and archiving the repo, I assume it's not relevant anymore.
